### ISSUE TITLE
Active tab is not recognizable

### ISSUE THREAD

**Issue by philipgiuliani** [trag1c/gleam-theme#1]
When using the bufferline:
```toml
[editor]
bufferline = "multiple"
```

the active tab is not highlighted:
![Screenshot](https://github.com/trag1c/gleam-theme/assets/5446019/54f7ca35-88a9-4e05-816d-8d06fb8b39a6)
